### ISSUE TITLE
(IMPORT FAILED): H:\ComfyUI\custom_nodes\ComfyUI-mnemic-nodes

### ISSUE THREAD

**Issue by Piscabo** [MNeMoNiCuZ/ComfyUI-mnemic-nodes#12]
File "H:\ComfyUI\custom_nodes\ComfyUI-mnemic-nodes\nodes\groq_api_llm.py", line 10, in <module>
    from ..utils.api_utils import make_api_request, load_prompt_options, get_prompt_content
ModuleNotFoundError: No module named 'ComfyUI-mnemic-nodes.utils.api_utils'

Cannot import H:\ComfyUI\custom_nodes\ComfyUI-mnemic-nodes module for custom nodes: No module named 'ComfyUI-mnemic-nodes.utils.api_utils'

**Comment by MNeMoNiCuZ** [comment]
Apologies.
It should be fixed now.

https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/commit/2a32aa861044cdcab652c598dd180fe7de28f735

Please grab an update and let me know if you still have any issues.
