### ISSUE TITLE
Any chance of adding a suffix as well?

### ISSUE THREAD

**Issue by DarkAlchy** [MNeMoNiCuZ/ComfyUI-mnemic-nodes#7]
Comfy saves images as prefix_number_.type, and that last _ is what would be great to have.

**Comment by MNeMoNiCuZ** [comment]
> Comfy saves images as prefix_number_.type, and that last _ is what would be great to have.

Could you explain a bit more please, and with a few examples.
I think it sounds doable, but I'm not sure I understand exactly what you mean.

**Comment by DarkAlchy** [comment]
Sure.
![image](https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/assets/10561690/85be1fbf-ca60-453f-bdc0-549e82c4e8dd)


![image](https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/assets/10561690/5ea7c87b-1d04-4f48-b9c5-eea99f97e1fa)

See that last underscore before the png file type?  Need that because we can't change that in comfy so his saves are how they are and we need caption text files to have the exact same name.  I have to take the same filenames and use a rename.py I wrote to add that underscore to them so I can train on the images.

**Comment by MNeMoNiCuZ** [comment]
Suffix should now be added. Let me know if you're having problems with it.

Please note:
I don't think updating this pack works with the ComfyUI manager yet. I haven't figured out how to push my updates to the version in ComfyUI Manager. So you're gonna have to do a manual update for now. Sorry.

**Comment by DarkAlchy** [comment]
Thank you.
