### ISSUE TITLE
Could you consider making the output path more flexible?

### ISSUE THREAD

**Issue by BoosterCore** [MNeMoNiCuZ/ComfyUI-mnemic-nodes#8]
I have a rather special requirement, wanting to output the text generated by Ollama in ComfyUI as a note document in notebook software Obsidian. Therefore, if this node could direct the target output path to my custom directory, that would be perfect!
![Screenshot 2024-06-21 010407](https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/assets/73834045/75818599-eb78-4ad7-aef7-84a30457a778)
Thank U very much！

**Comment by MNeMoNiCuZ** [comment]
As it is, I want to keep the outputs of the model to the /output/ directory.
But it doesn't sound very hard to allow any path. You could perhaps try to modify the node for yourself?

![image](https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/assets/60541708/6db7283d-eded-4ba8-93eb-301a73ea1110)


```
   def save_text_file(self, file_text, path, prefix='[time(%Y-%m-%d %H.%M.%S)]', counter_separator='_', counter_length=3, suffix='', output_extension='txt'):
        path = replace_tokens(path)
        prefix = replace_tokens(prefix)
        suffix = replace_tokens(suffix)

        # Safety check to ensure the extension is not empty
        if not output_extension.strip():
            raise ValueError("The output extension cannot be empty.")

        # Safety check to prevent directory traversal
        if '..' in path or any(esc in path for esc in ['..\\', '../']):
            raise ValueError("The specified path contains invalid characters that navigate outside the output directory.")

        # Check if the path is absolute
        if os.path.isabs(path):
            full_path = os.path.abspath(path)
        else:
            # Get the base output directory from folder_paths
            output_base_dir = get_output_directory()
            full_path = os.path.join(output_base_dir, path)
            full_path = os.path.abspath(full_path)

            # Ensure the path is within the allowed directory
            if not full_path.startswith(output_base_dir):
                raise ValueError("The specified path is outside the allowed output directory")

        if not os.path.exists(full_path):
            print(f"Warning: The path `{full_path}` doesn't exist! Creating it...")
            try:
                os.makedirs(full_path, exist_ok=True)
            except OSError as e:
                print(f"Error: The path `{full_path}` could not be created! Is there write access?\n{e}")

        if file_text.strip() == '':
            raise ValueError("There is no text specified to save! Text is empty.")

        separator = counter_separator
        number_padding = int(counter_length)
        file_extension = f'.{output_extension}'

        filename, counter = self.generate_filename(full_path, prefix, suffix, separator, number_padding, file_extension)
        file_path = os.path.join(full_path, filename)

        # Remove extension from output_name
        output_name = os.path.splitext(filename)[0]

        self.writeTextFile(file_path, file_text)

        return file_path, output_name
```

**Comment by BoosterCore** [comment]
Thanks！ I'll try it！

**Comment by BoosterCore** [comment]
Thank you so much! The code you provided works perfectly. I made a few adjustments and managed to create my own node!!!
![image](https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/assets/73834045/8b664172-2f51-465f-a0d2-38baa2d1a08e)

**Comment by Vigilence** [comment]
Path should be the default of what you want (/output/ directory) but we should be allowed to change it without having to edit code.

**Comment by MNeMoNiCuZ** [comment]
> @MNeMoNiCuZ Path should be the default of what you want (/output/ directory) but we should be allowed to change it without having to edit code. Forcing hardcoded paths etc is not the best experience for anyone.

There were security concerns brought up by the community of letting the node save files outside of the environment. It could be used for some adverse attacks hidden inside workflows, such as saving over important files in your operating system, by escaping the project folder. I think this makes sense to do some light step to avoid.

If you really need the files to be elsewhere, you can likely set up some script like [Belvedere](https://www.portablefreeware.com/index.php?id=1682), to monitor your folders and move files automatically, or a symbolic link between folders.
